### ISSUE TITLE
Concurrent map read and map write in EthSubscriptions.LegacyPoll

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1344]
I'm guessing the `timestamps` map is being read & written concurrently.

```
July 15th 2019, 11:26:12.650 | fatal error: concurrent map read and map write
  | July 15th 2019, 11:26:12.654 | goroutine 10886167 [running]:

  | July 15th 2019, 11:26:12.657 | #011/usr/local/go-1.12/src/runtime/panic.go:617 +0x72 fp=0xc13b5a4c28 sp=0xc13b5a4bf8 pc=0xaccd02

  | July 15th 2019, 11:26:12.657 | runtime.throw(0x1bd05c6, 0x21)

  | July 15th 2019, 11:26:12.658 | github.com/loomnetwork/loomchain/eth/polls.EthSubscriptions.LegacyPoll(0xc0675f5aa0, 0xc0675f5b00, 0xc0675f5b60, 0x0, 0xc043c525f8, 0x1f5b140, 0xc04758bf00, 0x7fb4609722c0, 0xc08a2bb5c0, 0xc05a3ece40, ...)

  | July 15th 2019, 11:26:12.658 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/eth/polls/eth_subscribe.go:138 +0x239 fp=0xc13b5a4fc8 sp=0xc13b5a4cf8 pc=0x17ad6f9

  | July 15th 2019, 11:26:12.658 | #011/usr/local/go-1.12/src/runtime/map_fast64.go:21 +0x1a8 fp=0xc13b5a4c50 sp=0xc13b5a4c28 pc=0xab0778

  | July 15th 2019, 11:26:12.658 | runtime.mapaccess1_fast64(0x1970220, 0xc0675f5b60, 0x70e0e2, 0x22)

  | July 15th 2019, 11:26:12.658 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/eth/polls/eth_subscribe.go:73 +0x95 fp=0xc13b5a4cf8 sp=0xc13b5a4c50 pc=0x17ac645

  | July 15th 2019, 11:26:12.658 | github.com/loomnetwork/loomchain/eth/polls.EthSubscriptions.resetTimestamp(0xc0675f5aa0, 0xc0675f5b00, 0xc0675f5b60, 0x0, 0xc043c525f8, 0x1f5b140, 0xc04758bf00, 0xc05a3ece40, 0x22, 0x70e0e2)

  | July 15th 2019, 11:26:12.659 | github.com/loomnetwork/loomchain/rpc.(*InstrumentingMiddleware).GetEvmFilterChanges(0xc0675f5bc0, 0xc05a3ece40, 0x22, 0xc08014af60, 0x10, 0xc00012e380, 0xc13b5a5428, 0xab2f95)

  | July 15th 2019, 11:26:12.659 | #011<autogenerated>:1 +0xa9 fp=0xc13b5a53c0 sp=0xc13b5a5318 pc=0x17d7599

  | July 15th 2019, 11:26:12.659 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/rpc/query_server.go:639 +0x29c fp=0xc13b5a52a8 sp=0xc13b5a4fc8 pc=0x17bd2fc

  | July 15th 2019, 11:26:12.659 | github.com/loomnetwork/loomchain/rpc.InstrumentingMiddleware.GetEvmFilterChanges(0x1f37e00, 0xc04758be00, 0x1f37e80, 0xc04758bee0, 0x1f84d20, 0xc0472f42d0, 0xc05a3ece40, 0x22, 0x0, 0x0, ...)

  | July 15th 2019, 11:26:12.659 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/rpc/instrumenting.go:187 +0xea fp=0xc13b5a5318 sp=0xc13b5a52a8 pc=0x17b433a

  | July 15th 2019, 11:26:12.659 | github.com/loomnetwork/loomchain/rpc.(*QueryServer).GetEvmFilterChanges(0xc0472f42d0, 0xc05a3ece40, 0x22, 0x0, 0x0, 0x0, 0x0, 0x0)

  | July 15th 2019, 11:26:12.659 | github.com/loomnetwork/loomchain/rpc.QueryService.GetEvmFilterChanges-fm(0xc05a3ece40, 0x22, 0x0, 0x0, 0x0, 0x0, 0x0)

  | July 15th 2019, 11:26:12.660 | runtime.call64(0xc08014af60, 0xc047680300, 0xc07ed78040, 0x1000000038)

  | July 15th 2019, 11:26:12.660 | reflect.Value.call(0x1973fa0, 0xc047680300, 0x13, 0x1b7e479, 0x4, 0xc08a2bb580, 0x1, 0x1, 0xc000c78d58, 0x0, ...)

  | July 15th 2019, 11:26:12.660 | #011/usr/local/go-1.12/src/reflect/value.go:308 +0xa4 fp=0xc13b5a56e8 sp=0xc13b5a5680 pc=0xb2bb14

  | July 15th 2019, 11:26:12.660 | #011/usr/local/go-1.12/src/runtime/asm_amd64.s:520 +0x3b fp=0xc13b5a5460 sp=0xc13b5a5410 pc=0xafb1db

  | July 15th 2019, 11:26:12.660 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/rpc/query_service.go:72 +0x46 fp=0xc13b5a5410 sp=0xc13b5a53c0 pc=0x17d3026

  | July 15th 2019, 11:26:12.660 | reflect.Value.Call(0x1973fa0, 0xc047680300, 0x13, 0xc08a2bb580, 0x1, 0x1, 0xc08a2bb580, 0x1, 0x1)

  | July 15th 2019, 11:26:12.660 | #011/usr/local/go-1.12/src/reflect/value.go:447 +0x461 fp=0xc13b5a5680 sp=0xc13b5a5460 pc=0xb2c091

  | July 15th 2019, 11:26:12.660 | github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/rpc/lib/server.makeJSONRPCHandler.func1(0x1f52140, 0xc08a2bb520, 0xc0e4cd3c00)

  | July 15th 2019, 11:26:12.661 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:145 +0x407 fp=0xc13b5a58c0 sp=0xc13b5a56e8 pc=0x1474867

  | July 15th 2019, 11:26:12.661 | github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/rpc/lib/server.handleInvalidJSONRPCPaths.func1(0x1f52140, 0xc08a2bb520, 0xc0e4cd3c00)

  | July 15th 2019, 11:26:12.661 | #011/usr/local/go-1.12/src/net/http/server.go:2375 +0x1d6 fp=0xc13b5a5980 sp=0xc13b5a5920 pc=0xeeefd6

  | July 15th 2019, 11:26:12.661 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:165 +0x9c fp=0xc13b5a58f8 sp=0xc13b5a58c0 pc=0x147522c

  | July 15th 2019, 11:26:12.661 | net/http.HandlerFunc.ServeHTTP(0xc0475dd600, 0x1f52140, 0xc08a2bb520, 0xc0e4cd3c00)

  | July 15th 2019, 11:26:12.661 | net/http.(*ServeMux).ServeHTTP(0xc047529040, 0x1f52140, 0xc08a2bb520, 0xc0e4cd3c00)

  | July 15th 2019, 11:26:12.661 | #011/usr/local/go-1.12/src/net/http/server.go:1995 +0x44 fp=0xc13b5a5920 sp=0xc13b5a58f8 pc=0xeed104

  | July 15th 2019, 11:26:12.662 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/rpc/query_service.go:143 +0x232 fp=0xc13b5a59e8 sp=0xc13b5a5980 pc=0x17d0612

  | July 15th 2019, 11:26:12.662 | #011/usr/local/go-1.12/src/net/http/server.go:1995 +0x44 fp=0xc13b5a5a10 sp=0xc13b5a59e8 pc=0xeed104

  | July 15th 2019, 11:26:12.662 | github.com/loomnetwork/loomchain/rpc.MakeQueryServiceHandler.func1(0x1f52140, 0xc08a2bb520, 0xc0e4cd3c00)

  | July 15th 2019, 11:26:12.662 | net/http.HandlerFunc.ServeHTTP(0xc0475dd620, 0x1f52140, 0xc08a2bb520, 0xc0e4cd3c00)

  | July 15th 2019, 11:26:12.662 | net/http.(*ServeMux).ServeHTTP(0xc047529100, 0x1f52140, 0xc08a2bb520, 0xc0e4cd3c00)

  | July 15th 2019, 11:26:12.662 | #011/usr/local/go-1.12/src/net/http/server.go:2375 +0x1d6 fp=0xc13b5a5a70 sp=0xc13b5a5a10 pc=0xeeefd6

  | July 15th 2019, 11:26:12.663 | github.com/loomnetwork/loomchain/rpc.stripPrefix.func1(0x1f52140, 0xc08a2bb520, 0xc0e4cd3b00)

  | July 15th 2019, 11:26:12.663 | github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x1f26c80, 0xc047529300, 0xf4240, 0x1f52140, 0xc08a2bb520, 0xc0e4cd3b00)

  | July 15th 2019, 11:26:12.663 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:179 +0xd0 fp=0xc13b5a5bb0 sp=0xc13b5a5b70 pc=0x1474030

  | July 15th 2019, 11:26:12.663 | #011/usr/local/go-1.12/src/net/http/server.go:1995 +0x44 fp=0xc13b5a5b10 sp=0xc13b5a5ae8 pc=0xeed104

  | July 15th 2019, 11:26:12.663 | net/http.(*ServeMux).ServeHTTP(0xc047529300, 0x1f52140, 0xc08a2bb520, 0xc0e4cd3b00)

  | July 15th 2019, 11:26:12.663 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/rpc/rpc_server.go:132 +0x19d fp=0xc13b5a5ae8 sp=0xc13b5a5a70 pc=0x17d0add

  | July 15th 2019, 11:26:12.663 | #011/usr/local/go-1.12/src/net/http/server.go:2375 +0x1d6 fp=0xc13b5a5b70 sp=0xc13b5a5b10 pc=0xeeefd6

  | July 15th 2019, 11:26:12.663 | net/http.HandlerFunc.ServeHTTP(0xc06773faa0, 0x1f52140, 0xc08a2bb520, 0xc0e4cd3b00)

  | July 15th 2019, 11:26:12.664 | #011<autogenerated>:1 +0x6c fp=0xc13b5a5bf0 sp=0xc13b5a5bb0 pc=0x147750c

  | July 15th 2019, 11:26:12.664 | github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x1f54180, 0xc073bd8540, 0xc0e4cd3b00)

  | July 15th 2019, 11:26:12.664 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:152 +0x317 fp=0xc13b5a5cc8 sp=0xc13b5a5bf0 pc=0x1476d17

  | July 15th 2019, 11:26:12.664 | #011/usr/local/go-1.12/src/net/http/server.go:1995 +0x44 fp=0xc13b5a5cf0 sp=0xc13b5a5cc8 pc=0xeed104

  | July 15th 2019, 11:26:12.664 | net/http.serverHandler.ServeHTTP(0xc0476a0270, 0x1f54180, 0xc073bd8540, 0xc0e4cd3b00)

  | July 15th 2019, 11:26:12.664 | github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/rpc/lib/server.(*maxBytesHandler).ServeHTTP(0xc0476813c0, 0x1f52140, 0xc08a2bb520, 0xc0e4cd3b00)

  | July 15th 2019, 11:26:12.664 | net/http.HandlerFunc.ServeHTTP(0xc0678933e0, 0x1f54180, 0xc073bd8540, 0xc0e4cd3b00)

  | July 15th 2019, 11:26:12.665 | #011/usr/local/go-1.12/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc13b5a5fd0 sp=0xc13b5a5fc8 pc=0xafce71

  | July 15th 2019, 11:26:12.665 | #011/usr/local/go-1.12/src/net/http/server.go:1878 +0x84c fp=0xc13b5a5fc8 sp=0xc13b5a5d20 pc=0xeec0cc

  | July 15th 2019, 11:26:12.665 | net/http.(*conn).serve(0xc07d7ccc80, 0x1f5a980, 0xc0520d9e80)

  | July 15th 2019, 11:26:12.665 | #011/usr/local/go-1.12/src/net/http/server.go:2774 +0xab fp=0xc13b5a5d20 sp=0xc13b5a5cf0 pc=0xef03bb

  | July 15th 2019, 11:26:12.665 | runtime.goexit()

  | July 15th 2019, 11:26:12.666 | github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/libs/common.TrapSignal(0xc0475ddcf0)

  | July 15th 2019, 11:26:12.666 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/abci/backend/tendermint.go:456 +0x57

  | July 15th 2019, 11:26:12.666 | github.com/loomnetwork/loomchain/abci/backend.(*TendermintBackend).RunForever(0xc00098a9a0)
```

**Comment by Sriep** [comment]
Fixed in https://github.com/loomnetwork/loomchain/pull/1346
