### ISSUE TITLE
Fix race condition in fnConsensus registry

### ISSUE THREAD

**Issue by pathornteng** [loomnetwork/loomchain#1388]
We got a node panic as follow due to some race condition. After investigating the code, we have found a potential culprit of this panic. The function `GetAll` of fnConsensus registry does not acquire mutex when reading map. https://github.com/loomnetwork/loomchain/blob/7496f9388e09c509fbc4a5d23c684e6b010929da/fnConsensus/registry.go#L39

```
  | August 2nd 2019, 08:36:28.430 | I[2019-08-02\|08:36:28.429] Using simple log event dispatcher | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:28.429 | I[2019-08-02\|08:36:28.429] VersionedCachingStore enabled                module=loom | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:27.837 | I[2019-08-02\|08:36:27.837] Loading Multi-Writer App Store               module=loom | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:25.829 | loom.service: Service hold-off time over, scheduling restart. | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.672 | loom.service: Failed with result 'exit-code'. | warning | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.672 | loom.service: Unit entered failed state. | notice | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.671 | loom.service: Main process exited, code=exited, status=2/INVALIDARGUMENT | notice | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.518 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/consensus/reactor.go:169 +0x1ba | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.517 | #011/usr/local/go-1.12/src/runtime/proc.go:307 | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.517 | github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusReactor).gossipDataRoutine(0xc0008e8f80, 0x1fd54a0, 0xc063ecaf00, 0xc0f3324c30) | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.517 | goroutine 90532797 [sleep]: | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.517 | time.Sleep(0x5f5e100) | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.517 | #011/tmp/gopath-jenkins-loom-sdk-pipeline3-1180/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/consensus/reactor.go:545 +0x223 | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.517 | created by github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusReactor).AddPeer | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.517 | runtime.goparkunlock(...) | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.517 | #011/usr/local/go-1.12/src/runtime/time.go:105 +0x159 | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.516 | #011/usr/local/go-1.12/src/net/http/transport.go:1677 +0x1a3 | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.516 | created by net/http.(*Transport).dialConn | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.516 | #011/usr/local/go-1.12/src/bufio/bufio.go:100 +0x10f | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.516 | #011/usr/local/go-1.12/src/net/http/transport.go:1357 +0xadb | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.516 | bufio.(*Reader).Peek(0xc0c9434ba0, 0x1, 0x0, 0x0, 0x1, 0xc1213e8c00, 0x0) | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.516 | #011/usr/local/go-1.12/src/bufio/bufio.go:138 +0x4f | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.516 | net/http.(*persistConn).readLoop(0xc06c666120) | info | test-z-us1-dappchains-2-aws3

  | August 2nd 2019, 08:36:23.515 | net/http.(*persistConn).Read(0xc06c666120, 0xc05d415000, 0x1000, 0x1000, 0xc027185c88, 0xad1245, 0xc0f643b020) | info | test-z-us1-dappchains-2-aws3

```

**Comment by pathornteng** [comment]
This issue has been resolved.
