### ISSUE TITLE
Wrong Block.Header.AppHash Error during node synching

### ISSUE THREAD

**Issue by riccardopersiani** [loomnetwork/loomchain#1464]
Tried several times to synch the node, even with the following tutorial (without systemd) but the node always freeze after a while: https://loomx.io/developers/en/jump-start-extdev-plasma-us1.html#start-the-node

```
I[2019-09-03|15:01:03.972] Executed block                               module=state height=7709379 validTxs=0 invalidTxs=1
I[2019-09-03|15:01:03.980] Updates to validators                        module=state updates=DF08C75CA88DF9EB71E78260A5F41DEEE5A8C93E:10,E7D1FF41D2B458EF4C3C8996F02E46C2FFB33C29:10,3DEB26D8718244502E46DDE48D651ADA098071AA:10,F5278DA47C67FCEEE4AE160C4B3396BEA45E7753:10
I[2019-09-03|15:01:03.980] commit took 0.000215 seconds-----
           module=loom
I[2019-09-03|15:01:03.980] Committed state                              module=state height=7709379 txs=1 appHash=C2C8D5DA80960506249610727B148CA0B2B629CCE402A5A43931D3D37D679912
I[2019-09-03|15:01:03.988] Indexed block                                module=txindex height=7709379
panic: Panicked questionably: Failed to process committed block (7709380:593CF9832DBC626FBFBD45F8E155BECF61BF7E9C1344677AD37832F26F372AC8): Wrong Block.Header.AppHash.  Expected C2C8D5DA80960506249610727B148CA0B2B629CCE402A5A43931D3D37D679912, got D9113E034BC138A598412F17D1D138696E04C68B8EC5F33B09AF1E1F38969395

goroutine 162 [running]:
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/libs/common.PanicQ(...)
        /tmp/gopath-jenkins-loom-sdk-pipeline3-1213/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/libs/common/errors.go:245
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc0434c8680)
        /tmp/gopath-jenkins-loom-sdk-pipeline3-1213/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:341 +0x1991
created by github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
        /tmp/gopath-jenkins-loom-sdk-pipeline3-1213/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:118 +0x84
```

**Comment by mattkanwisher** [comment]
@adyromantika

**Comment by adyromantika** [comment]
@riccardopersiani did you increase the open files limit as described here? https://loomx.io/developers/en/jump-start-extdev-plasma-us1.html#open-files-limit

Wrong Block.Header.AppHash can occur if it fails to open db files due to open files limit being exhausted.
