### ISSUE TITLE
Investigate critical failure in IAVLStore after pruning

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#610]
Occasionally nodes fail with:
```
E[14016-01-14|04:58:09.772] CONSENSUS FAILURE!!!
module=consensus
err="Value missing for hash 5cb20dea6ba50b7a9e847bb4cc6f212d82bd9c0605c22df1386a3327947175f0 corresponding to nodeKey n\\\ufffd\r\ufffdk\ufffd\u000bz\ufffd\ufffd{\ufffd\ufffdo!-\ufffd\ufffd\ufffd\u0006\u0005\ufffd-\ufffd8j3'\ufffdqu\ufffd" stack="goroutine 188 [running]:
runtime/debug.Stack(0xc00e4c85b0, 0x16fff00, 0xc00b1af920)
    /usr/local/go1.11.1/src/runtime/debug/stack.go:24 +0xa7
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc00018d880, 0x1ad65b0)
    /tmp/gopath-jenkins-loom-sdk-pipeline3-727/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/consensus/state.go:576 +0x57
panic(0x16fff00, 0xc00b1af920)
    /usr/local/go1.11.1/src/runtime/panic.go:513 +0x1b9
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/iavl.(*nodeDB).GetNode(0xc000d5d590, 0xc00b4bf600, 0x20, 0x20, 0x0)
    /tmp/gopath-jenkins-loom-sdk-pipeline3-727/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/iavl/nodedb.go:78 +0x530
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/iavl.(*Node).getRightNode(0xc009be8b00, 0xc00d574440, 0xc009be8bb0)
    /tmp/gopath-jenkins-loom-sdk-pipeline3-727/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/iavl/node.go:355 +0x73
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/iavl.(*Node).calcHeightAndSize(0xc009be8b00, 0xc00d574440)
    /tmp/gopath-jenkins-loom-sdk-pipeline3-727/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/iavl/node.go:360 +0x5b
github.com/loomnetwork/loomchain/vendor/github.com/tendermint/iavl.(*MutableTree).recursiveSet(0xc001254600, 0xc00c5e08f0, 0xc009d2b020, 0x22, 0x22, 0xc00e3e8090, 0x8, 0x40, 0xc00b4a48a0, 0x8, ...)
    /tmp/gopath-jenkins-loom-sdk-pipeline3-727/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/iavl/mutable_tree.go:134 +0x9c6
github.com/loomnetwork/loomchain/vendor/githu
```

I'm 99% sure that is caused by pruning of the IAVL store, there must be a bug in `MutableTree.DeleteVersion()` that fails to preserve nodes that are still referenced in newer versions of the tree. This happened with the older `iavl` package too, so this bug has been around for a while. Ideally we replace the current IAVL store with a more space efficient one that doesn't require pruning, thus avoiding this bug entirely.

**Comment by enlight** [comment]
Closing this since we don't prune using `DeleteVersion()` anymore, so no point spending any more time looking at it.
