### ISSUE TITLE
Add request validation to Coin Go contract

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#902]
Most of the methods in the coin contract don't validate the fields in the request before attempting to unmarshal them https://github.com/loomnetwork/loomchain/blob/master/builtin/plugins/coin/coin.go

So when some of those request fields are `nil` the node panics, and then we see an alert:
```
message:  E[27036-03-27|09:30:36.869] Panic in RPC HTTP handler                    module=query-server err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 1596945 [running]:\nruntime/debug.Stack(0xc0524a4590, 0x1913ac0, 0x2bd15c0)\n\t/usr/local/go-1.12/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc064cb95c0, 0x1e93c80, 0xc00be8d250, 0xbf1eee8f33ca4292, 0x5c0b9eb882f4, 0x2c38860, 0xc00af8e700)\n\t/tmp/gopath-jenkins-loom-sdk-pipeline3-895/src/github.com/loomnetwork/loomchain/vendor/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:134 +0x552\npanic(0x1913ac0, 0x2bd15c0)\n\t/usr/local/go-1.12/src/runtime/panic.go:522 +0x1b5\ngithub.com/loomnetwork/go-loom.UnmarshalAddressPB(...)\n\t/tmp/gopath-jenkins-loom-sdk-pipeline3-895/src/github.com/loomnetwork/go-loom/address.go:83\ngithub.com/loomnetwork/loomchain/builtin/plugins/coin.(*Coin).BalanceOf(0x2c5ffd8, 0x1eae360, 0xc064cb97c0, 0xc02f29fb30, 0x0, 0x0, 0x0)\n\t/tmp/gopath-jenkins-loom-sdk-pipeline3-895/src/github.com/loomnetwork/loomchain/builtin/plugins/coin/coin.go:211 +0x5a\nreflect.Value.call(0xc0002b6400, 0xc00013f240, 0x13, 0x1ad9f28, 0x4, 0xc0524a4b58, 0x3, 0x3, 0x0, 0x0, ...)\n\t/usr/local/go-1.12/src/reflect/value.go:447 +0x461\nreflect.Value.Call(0xc0002b6400, 0xc00013f240, 0x13, 0xc0524a4b58, 0x3, 0x3, 0x0, 0x5c9b42b6, 0xc064cb97c0)\n\t/usr/local/go-1.12/src/reflect/value.go:308 +0xa4\ngithub.com/loomnetwork/go-loom/plugin/contractpb.(*RequestDispatcher).doCall(0xc0002b4d80, 0x3, 0x1a80fe0, 0xc064cb97c0, 0xc06c4d0300, 0x1eaa340, 0xc007f773f0, 0xc06cb56b00)\n\t/tmp/gopath-jenkins-loom-sdk-pipeline3-895/src/github.com/loomnetwork/go-loom/plugin/contractpb/request_dispatcher.go:107 +0x56e\ngithub.com/loomnetwork/go-loom/plugin/contractpb.(*RequestDispatcher).StaticCall(0xc0002b4d80, 0x1ead480, 0xc007f773f0, 0xc06c4d0300, 0x14, 0x14, 0xc000963bb0)\n\t/tmp/gopath-jenkins-loom-sdk-pipeline3-895/src/github.com/loo
```

Need to add request validation to this contract, the validation checks may break replay though, so perhaps the validation should be enabled by a feature flag.

**Comment by enlight** [comment]
Resolved
